### ISSUE TITLE
关于DSL的查询文档和最佳实践

### ISSUE THREAD

**Issue by guajiguaji-dd** [wakeadmin/components#14]
### DSL查询文档
在官方文档好像也只有个导图图片 不能搜索查询某个字段
### 最佳实践
如果方便的话，可以提供一个基于这个组件库的示例项目吗？ 
或者有更多的封装，对简单的CRUD操作 通过配置就可以完成 这样的项目拿来学习使用

**Comment by njikm2010** [comment]
> 在官方文档好像也只有个导图图片 不能搜索查询某个字段

关于DSL查询的问题 ，很抱歉我们暂时提供不了对应的在线搜索能力，不过你可以打开对应的xmind文件进行查询；

----


> 如果方便的话，可以提供一个基于这个组件库的示例项目吗？
> 或者有更多的封装，对简单的CRUD操作 通过配置就可以完成 这样的项目拿来学习使用

可以参考这个[链接](https://codesandbox.io/p/sandbox/wakeadmin-components-fc4x8x)
